config/routes.rb
Rails.application.routes.draw do
  root 'quotes#index'
  resources :quotes
  get 'about', to: 'quotes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: { maximum: 140, minimum: 3}
  validates :author, presence: true, length: { maximum: 50, minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end
  
  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid? 
      flash[:error] = '<strong>Could not save.</strong> The data entered is invalid.'
    end
    redirect_to root_path
  end
  
    def about
    end
  
  private
  
  def quote_params
    params.require(:quote).permit(:saying, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="row">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
      <div class="col-3">
        <%= link_to root_path, class: 'logo' do %>
          <div class="circle">
          <br />
          You know.
          <br />
          We know.
          <br />
          WYO.
         </div>
        <% end %>
      </div>
      <div class="col col-sm-4 hidden-xs-down slogan">
        Splurting out unsolicited commentary about life in good ol' Wyoming since 2019
      </div>
      <div class="col-10 offset-1 offset-sm-0 col-sm-5 links">
        <!-- Button trigger modal -->
        <%= link_to 'Contribute', '#', data: {toggle: 'modal', target: '#myModal'} %>
        &nbsp;&nbsp;
        <%= link_to 'About', about_path %>
      </div>
    </header>
    


    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModal">Contribute Your Quote</h4>
          </div>
          <%= simple_form_for Quote.new do |f| %>
            <div class="modal-body">
              <%= f.input :saying, label: "You know you're in Wyoming when..", placeholder: "there are more antelope than cars on the road" %>
              <br />
              <%= f.input :author, label: "Who is the author of the quote?", placeholder: "Sarah C." %>            
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Create', class: 'btn btn-danger' %>
            </div>
        <% end %>
          </div>
        </div>
      </div>
    </div>

    
    <hr />
    
    <br class="clear" />
    
    <div class= "container">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
        <% end %>
      <%= yield %>
    </div>
    
    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-6">
            <%= link_to "This isn't enough, I need more", root_path, class: 'next-quote' %>
          </div>
          <div class="col-12 col-sm-6 footer-blurb">
            Proudly hacked by Wyomingite <a href="https://sarahmaecrank.netlify.com">Sarah Mae</a><br />
            Want to build your own Splurty Web App? - <a href="https://online.bootcampspot.com">Learn how to code here</a>
          </div>
        </div>
      </div>
    </div>
    
  </body>
</html>

app/views/quotes/about.html.erb
<div class="col-10 offset-1 about">
  <h1>About Splurty</h1>
  
   <p>
    Splurty was built by <a target="_blank" href="https://sarahmaecrank.netlify.com">Sarah Mae Crank</a>. Sarah is an aspiring web developer who spent her childhood roaming the plains and mountains of Wyoming. Knowing that there is no place like it, she decided to make a splurty to share its wonders.
  </p>

  <p>
    If you want to learn how to code - start <a target="_blank" href="https://online.bootcampspot.com"> here</a>.
  </p>
  
  <div class="row">
    <div class="col-12 col-sm-4">
      <%= image_tag 'sarah.jpg', class: 'img-fluid' %>
    </div>

    <div class="col-12 col-sm-7 offset-sm-1">
      <h2 class="text-center">Sarah Mae Crank</h2>
      <br />
      <p>
        Sarah Crank is a Project Lead in the Creative Services department at Feld Entertainment, Inc. in Palmetto, FL. She facilitates the ideation, creation, and distribution of marketing materials for all Marvel Universe LIVE! shows domestically and internationally. Currently, she is in the process of completing the Coding Boot Camp through the University of Central Florida in hopes of becoming more marketable in the job search process.
      </p>
    </div>
  </div>
</div>

<br class="clear" />
<br />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<h1>
  <span>SPLURTY / No. <%= @quote.id %></span>
</h1>
<h2>You know you're in Wyoming when ...</h2>

<h1><%= @quote.saying %></h1>
<h2 class="float-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />